export const Database = () => {
    return [
        { url:"https://static1.squarespace.com/static/55f32473e4b029b54a7228d2/t/59a75f87e9bfdf4f73cc90ee/1504143995473/HACKSAW+RIDGE+-+MOT+CREATIVE.jpg?format=500w", title: "Narcos", desc:"While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type: "featured"},

          { url: "https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_SY298_CR0,0,201,298_AL_.jpg", title: "Venom", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"popular" },
          { url: "https://m.media-amazon.com/images/M/MV5BNzIxMjYwNDEwN15BMl5BanBnXkFtZTgwMzk5MDI3NTM@._V1_SY298_CR0,0,201,298_AL_.jpg", title: "Jurassic park", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"popular" },
          { url: "https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_SY298_CR0,0,201,298_AL_.jpg", title: "Incredibles", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard",type:"popular"  },
          { url: "https://m.media-amazon.com/images/M/MV5BYTNhZGU3YjAtMzg0OC00ZjdlLWIwYzItNzBjYjhkNWFkZWViXkEyXkFqcGdeQXVyMjYwNDA2MDE@._V1_SY298_CR1,0,201,298_AL_.jpg", title: "Riverdale", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"popular"  },
          { url: "https://m.media-amazon.com/images/M/MV5BMTU0MTI0MDAyM15BMl5BanBnXkFtZTgwMDg5MzYyNTM@._V1_SY298_CR1,0,201,298_AL_.jpg", title: "Handsmaids tale", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"popular"  },
          { url: "https://m.media-amazon.com/images/M/MV5BMjM2MTA5NjIwNV5BMl5BanBnXkFtZTgwNjI2OTMxNTM@._V1_SY298_CR0,0,201,298_AL_.jpg", title: "Westworld", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"popular"  },
  
          { url: "https://m.media-amazon.com/images/M/MV5BMTUwODAxMzMwNF5BMl5BanBnXkFtZTcwMTk3MTQ5Nw@@._V1_SY298_CR0,0,201,298_AL_.jpg", title: "Glass house", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"horror" },
          { url: "https://m.media-amazon.com/images/M/MV5BY2E1NmRjNDctOGYwZC00MWU2LWI3MmYtNTRiOGY2OTgzM2JhXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_SX201_CR0,0,201,298_AL_.jpg", title: "A night in the cabin", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"horror" },
          { url: "https://m.media-amazon.com/images/M/MV5BMjA5NzQ1NTgwNV5BMl5BanBnXkFtZTcwNjUxMzUzMw@@._V1_SY298_CR0,0,201,298_AL_.jpg", title: "Saw IV", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard",type:"horror"  },
          { url: "https://m.media-amazon.com/images/M/MV5BODM5ZTc0NTktY2M0My00NDU3LWI4MDUtY2QwMjdmMmZjODU0XkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SY298_CR1,0,201,298_AL_.jpg", title: "Scream", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"horror"  },
          { url: "https://m.media-amazon.com/images/M/MV5BZGI5ZTU2M2YtZWY4MC00ZDFhLTliYTItZTk1NjdlN2NkMzg2XkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_SX201_CR0,0,201,298_AL_.jpg", title: "American Psycho", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"horror"  },
          { url: "https://m.media-amazon.com/images/M/MV5BMTkxNzkyNzAxNV5BMl5BanBnXkFtZTgwNzY0MjYzMzI@._V1_SY298_CR4,0,201,298_AL_.jpg", title: "Star Wars", desc: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", type:"horror"  },
        ];
  };